name: Java Test

on:
  pull_request:
    branches:
      - main
    push:
      branches:
        - main
jobs:
  build:git
  name: Test on Windows
  runs-on: window-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: set up jdk
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '24'
    - name: Build and test on windows
      run: nvm clean verify






